language: python
python:
  - "3.3"
install:
  - "pip install coverage --use-mirrors"
  - "pip install pep8 --use-mirrors"
  - "pip install pyflakes --use-mirrors"
before_script:
  - "pep8 --max-line-length=160 ."
  - "pyflakes ."
  - export QINIU_ACCESS_KEY="X0XpjFmLMTJpHB_ESHjeolCtipk-1U3Ok7LVTdoN"
  - export QINIU_SECRET_KEY="wenlwkU1AYwNBf7Q9cCoG4VT_GYyrHE9AS_R2u81"
  - export QINIU_TEST_BUCKET="pysdk"
  - export QINIU_TEST_DOMAIN="pysdk.qiniudn.com"
  - export QINIU_TEST_ENV="travis"
  - export PYTHONPATH="$PYTHONPATH:."

