sudo: false
language: python
python:
- '2.6.9'
- '2.7'
- '3.4'
- '3.5'
install:
- pip install flake8
- pip install pytest
- pip install pytest-cov
- pip install requests
- pip install scrutinizer-ocular
before_script:
- export QINIU_TEST_BUCKET="pythonsdk"
- export QINIU_TEST_DOMAIN="pythonsdk.qiniudn.com"
- export QINIU_TEST_ENV="travis"
- export PYTHONPATH="$PYTHONPATH:."
script:
- if [[ "$TRAVIS_PYTHON_VERSION" != "2.6.9" ]]; then flake8 --show-source --max-line-length=160 .; fi
- py.test --cov qiniu
- if [[ "$TRAVIS_PYTHON_VERSION" != "2.6.9" ]]; then ocular --data-file .coverage; fi
deploy:
  provider: pypi
  user: qiniusdk
  password:
    secure: N2u9xzhncbziIhoDdpaCcr7D3lW/N7AOIZDpx+M5QW0lPqIXkZDioOTZ7b4QNwx/XFMu6tdeK79A2Wg7T9/8VfEWDd2bYL7a1J7spoFJi9k3HVHHiFBmg7vXr1OGn3D51xqsrq3Kh9uRP150a5CA2qxYabKb6b6dn5QhOTPhfFY=
  on:
    tags: true
